### ISSUE TITLE
local_configws Plugin scaffold

### ISSUE THREAD

**Issue by dvdcastro** [sofhouse/moodle-local_configws#1]
### Story

As a user I can install and configure `local_configws`

### AC

1. Exists new plugin called `local_configws` and can be installed without problems
2. The plugin has no settings
3. Catalyst build should be added.
```yaml
name: ci

on: [push, pull_request]

jobs:
  test:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    # secrets:
    #   # Required if you plan to publish (uncomment the below)
    #   moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
    with:
      disable_release : true
```
The `version.php` file should read `$plugin->supported = [405, 405];`
